import type { AbilityScores } from '@/types/database';

export interface CharacterTemplate {
  id: string;
  name: string;
  tagline: string;
  race: string;
  className: string;
  subclass: string;
  background: string;
  stats: AbilityScores;
  skills: string[];
  features: string[];
  equipment: string[];
  maxHp: number;
  armorClass: number;
  speed: number;
  appearance: string;
  ideals: string;
  bonds: string;
  flaws: string;
  backstoryPrompt: string;
  portraitKey: string;
  skinTint: string;
}

/** Exactly 10 allowed presets — AI and manual forge must stay inside this fence. */
export const CHARACTER_TEMPLATES: CharacterTemplate[] = [
  {
    id: 'iron-paladin',
    name: 'Iron Paladin',
    tagline: 'Oathbound steel and stubborn mercy',
    race: 'Human',
    className: 'Paladin',
    subclass: 'Oath of Devotion',
    background: 'Soldier',
    stats: { STR: 16, DEX: 10, CON: 14, INT: 8, WIS: 12, CHA: 14 },
    skills: ['Athletics', 'Intimidation', 'Persuasion', 'Religion'],
    features: ['Divine Sense', 'Lay on Hands', 'Fighting Style: Defense'],
    equipment: ['Longsword', 'Shield', 'Chain Mail', 'Holy Symbol', 'Explorer Pack'],
    maxHp: 12,
    armorClass: 18,
    speed: 30,
    appearance: 'Scarred jaw, polished mail, eyes that do not blink first',
    ideals: 'Protect the weak even when the world laughs',
    bonds: 'Sworn to a ruined chapel and the three who still pray there',
    flaws: 'Will die before breaking a promise — even a stupid one',
    backstoryPrompt: 'Who did you fail to save, and what oath did that birth?',
    portraitKey: 'Paladin',
    skinTint: '#c4a574',
  },
  {
    id: 'shadow-rogue',
    name: 'Shadow Rogue',
    tagline: 'Quiet knives, louder secrets',
    race: 'Half-Elf',
    className: 'Rogue',
    subclass: 'Thief',
    background: 'Criminal',
    stats: { STR: 8, DEX: 16, CON: 12, INT: 14, WIS: 12, CHA: 12 },
    skills: ['Stealth', 'Sleight of Hand', 'Acrobatics', 'Deception', 'Perception', 'Investigation'],
    features: ['Sneak Attack', 'Thieves Cant', 'Cunning Action'],
    equipment: ['Shortsword', 'Shortbow', 'Leather Armor', 'Thieves Tools', 'Burglar Pack'],
    maxHp: 10,
    armorClass: 14,
    speed: 30,
    appearance: 'Ink-dark cloak, quick smile that never reaches the eyes',
    ideals: 'Information is the only honest currency',
    bonds: 'Still owes a debt to a crew that may already be dead',
    flaws: 'Cannot resist one more look inside a locked thing',
    backstoryPrompt: 'What job went wrong, and who still wants your head?',
    portraitKey: 'Rogue',
    skinTint: '#64748b',
  },
  {
    id: 'wild-barbarian',
    name: 'Wild Barbarian',
    tagline: 'Rage with a pulse and a punchline',
    race: 'Half-Orc',
    className: 'Barbarian',
    subclass: 'Path of the Berserker',
    background: 'Outlander',
    stats: { STR: 16, DEX: 14, CON: 16, INT: 8, WIS: 10, CHA: 10 },
    skills: ['Athletics', 'Survival', 'Intimidation', 'Animal Handling'],
    features: ['Rage', 'Unarmored Defense', 'Reckless Attack'],
    equipment: ['Greataxe', 'Handaxes x2', 'Explorer Pack', 'Javelins'],
    maxHp: 14,
    armorClass: 14,
    speed: 30,
    appearance: 'Braided scars, bone charms, laugh like a landslide',
    ideals: 'Strength means standing between the storm and your people',
    bonds: 'Carries a totem from a clan that cast them out',
    flaws: 'When the red haze hits, diplomacy is already dead',
    backstoryPrompt: 'What exile brand do you wear, and who still calls you kin?',
    portraitKey: 'Barbarian',
    skinTint: '#b45309',
  },
  {
    id: 'hex-sorcerer',
    name: 'Hex Sorcerer',
    tagline: 'Born wrong, casting right',
    race: 'Tiefling',
    className: 'Sorcerer',
    subclass: 'Wild Magic',
    background: 'Hermit',
    stats: { STR: 8, DEX: 14, CON: 14, INT: 10, WIS: 12, CHA: 16 },
    skills: ['Arcana', 'Persuasion', 'Insight', 'Religion'],
    features: ['Font of Magic', 'Wild Magic Surge', 'Innate Infernal Magic'],
    equipment: ['Arcane Focus', 'Dagger', 'Component Pouch', 'Explorer Pack'],
    maxHp: 8,
    armorClass: 12,
    speed: 30,
    appearance: 'Ember eyes, ash-gray horns, handwriting that smolders',
    ideals: 'Power is a language — speak it before it speaks you',
    bonds: 'A sealed letter from a parent who was not human',
    flaws: 'Curious about catastrophic magic the way moths love lamps',
    backstoryPrompt: 'When did your magic first break something you loved?',
    portraitKey: 'Sorcerer',
    skinTint: '#7c3aed',
  },
  {
    id: 'blade-bard',
    name: 'Blade Bard',
    tagline: 'Steel tempo and cutting verses',
    race: 'Human',
    className: 'Bard',
    subclass: 'College of Swords',
    background: 'Entertainer',
    stats: { STR: 10, DEX: 14, CON: 12, INT: 12, WIS: 10, CHA: 16 },
    skills: ['Performance', 'Persuasion', 'Deception', 'Acrobatics', 'Stealth'],
    features: ['Bardic Inspiration', 'Spellcasting', 'Blade Flourish'],
    equipment: ['Rapier', 'Leather Armor', 'Lute', 'Diplomat Pack', 'Dagger'],
    maxHp: 10,
    armorClass: 13,
    speed: 30,
    appearance: 'Stage makeup half-wiped, dueling scars like punctuation',
    ideals: 'Every fight is a song — finish on the right note',
    bonds: 'Chasing a rival who stole their masterpiece',
    flaws: 'Needs an audience, even when stealth would be smarter',
    backstoryPrompt: 'Whose applause do you still hear when you sleep?',
    portraitKey: 'Bard',
    skinTint: '#db2777',
  },
  {
    id: 'oathbreaker-antihero',
    name: 'Ashen Antihero',
    tagline: 'Fell from grace, kept the armor',
    race: 'Human',
    className: 'Paladin',
    subclass: 'Oathbreaker',
    background: 'Noble',
    stats: { STR: 14, DEX: 10, CON: 14, INT: 10, WIS: 10, CHA: 16 },
    skills: ['History', 'Persuasion', 'Intimidation', 'Athletics'],
    features: ['Lay on Hands', 'Divine Smite', 'Broken Oath Aura'],
    equipment: ['Longsword', 'Shield', 'Breastplate', 'Signet Ring', 'Fine Clothes'],
    maxHp: 12,
    armorClass: 16,
    speed: 30,
    appearance: 'Blackened crest, perfume over blood, smile like a verdict',
    ideals: 'If the gods abandon you, become the consequence',
    bonds: 'A house name that opens doors and closes graves',
    flaws: 'Cannot refuse a chance to prove they were right to fall',
    backstoryPrompt: 'Which vow did you shatter, and who still wears the scar?',
    portraitKey: 'Paladin',
    skinTint: '#44403c',
  },
  {
    id: 'war-cleric',
    name: 'War Cleric',
    tagline: 'Prayers with blunt force trauma',
    race: 'Dwarf',
    className: 'Cleric',
    subclass: 'War Domain',
    background: 'Acolyte',
    stats: { STR: 14, DEX: 10, CON: 14, INT: 10, WIS: 16, CHA: 10 },
    skills: ['Medicine', 'Religion', 'Insight', 'Athletics'],
    features: ['Spellcasting', 'War Priest', 'Channel Divinity'],
    equipment: ['Warhammer', 'Shield', 'Scale Mail', 'Holy Symbol', 'Priest Pack'],
    maxHp: 10,
    armorClass: 16,
    speed: 25,
    appearance: 'Braided beard, dented helm, incense in the armor joints',
    ideals: 'Faith without courage is just decoration',
    bonds: 'Serves a battlefield shrine built from enemy steel',
    flaws: 'Sermons mid-combat; allies love and hate it',
    backstoryPrompt: 'Which god answered you in the mud, and what did they demand?',
    portraitKey: 'Paladin',
    skinTint: '#b45309',
  },
  {
    id: 'war-wizard',
    name: 'War Wizard',
    tagline: 'Equations that explode on contact',
    race: 'High Elf',
    className: 'Wizard',
    subclass: 'School of Evocation',
    background: 'Sage',
    stats: { STR: 8, DEX: 14, CON: 12, INT: 16, WIS: 12, CHA: 10 },
    skills: ['Arcana', 'History', 'Investigation', 'Insight'],
    features: ['Spellcasting', 'Arcane Recovery', 'Sculpt Spells'],
    equipment: ['Spellbook', 'Quarterstaff', 'Component Pouch', 'Scholar Pack'],
    maxHp: 8,
    armorClass: 12,
    speed: 30,
    appearance: 'Ink-stained fingers, sharp ears, goggles scorched at the rims',
    ideals: 'Knowledge should be tested until it screams',
    bonds: 'A master who vanished mid-experiment',
    flaws: 'Treats living allies like variables in a proof',
    backstoryPrompt: 'What experiment succeeded too well?',
    portraitKey: 'Sorcerer',
    skinTint: '#0284c7',
  },
  {
    id: 'folk-fighter',
    name: 'Folk Fighter',
    tagline: 'Village steel, city problems',
    race: 'Human',
    className: 'Fighter',
    subclass: 'Champion',
    background: 'Folk Hero',
    stats: { STR: 16, DEX: 12, CON: 14, INT: 10, WIS: 12, CHA: 10 },
    skills: ['Athletics', 'Survival', 'Animal Handling', 'Perception'],
    features: ['Second Wind', 'Fighting Style: Dueling', 'Action Surge'],
    equipment: ['Longsword', 'Shield', 'Chain Mail', 'Explorer Pack'],
    maxHp: 12,
    armorClass: 18,
    speed: 30,
    appearance: 'Calloused hands, patched cloak, posture like a fence post',
    ideals: 'Ordinary people deserve extraordinary backup',
    bonds: 'The mill town that still paints your name on the gate',
    flaws: 'Trusts the wrong underdog every single time',
    backstoryPrompt: 'Which local tyrant did you humble, and who noticed?',
    portraitKey: 'Barbarian',
    skinTint: '#ca8a04',
  },
  {
    id: 'cursed-warlock',
    name: 'Cursed Warlock',
    tagline: 'Borrowed power, expensive interest',
    race: 'Human',
    className: 'Warlock',
    subclass: 'The Fiend',
    background: 'Charlatan',
    stats: { STR: 8, DEX: 12, CON: 14, INT: 12, WIS: 10, CHA: 16 },
    skills: ['Deception', 'Persuasion', 'Arcana', 'Intimidation'],
    features: ['Pact Magic', 'Dark One\'s Blessing', 'Eldritch Invocations'],
    equipment: ['Leather Armor', 'Arcane Focus', 'Dagger', 'Scholar Pack'],
    maxHp: 10,
    armorClass: 12,
    speed: 30,
    appearance: 'Gold smile, shadow under the nails, contract burn on the wrist',
    ideals: 'Freedom is worth any signature',
    bonds: 'A patron who texts in nightmares',
    flaws: 'Will gamble soul-adjacent assets when bored',
    backstoryPrompt: 'What did you sell, and what clause did you miss?',
    portraitKey: 'Sorcerer',
    skinTint: '#9f1239',
  },
];

export function getTemplate(id: string): CharacterTemplate | undefined {
  return CHARACTER_TEMPLATES.find((template) => template.id === id);
}

export function listTemplateIds(): string[] {
  return CHARACTER_TEMPLATES.map((template) => template.id);
}
